# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jannis/CGAL/CGAL-4.2/demo/Red_blue_merge_demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jannis/CGAL/CGAL-4.2/demo/Red_blue_merge_demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jannis/CGAL/CGAL-4.2/demo/Red_blue_merge_demo/CMakeFiles /home/jannis/CGAL/CGAL-4.2/demo/Red_blue_merge_demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jannis/CGAL/CGAL-4.2/demo/Red_blue_merge_demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redblue

# Build rule for target.
redblue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redblue
.PHONY : redblue

# fast build rule for target.
redblue/fast:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/build
.PHONY : redblue/fast

# target to build an object file
MyWindow.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow.o
.PHONY : MyWindow.o

# target to preprocess a source file
MyWindow.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow.i
.PHONY : MyWindow.i

# target to generate assembly for a file
MyWindow.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow.s
.PHONY : MyWindow.s

# target to build an object file
MyWindow_files.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_files.o
.PHONY : MyWindow_files.o

# target to preprocess a source file
MyWindow_files.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_files.i
.PHONY : MyWindow_files.i

# target to generate assembly for a file
MyWindow_files.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_files.s
.PHONY : MyWindow_files.s

# target to build an object file
MyWindow_operations.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_operations.o
.PHONY : MyWindow_operations.o

# target to preprocess a source file
MyWindow_operations.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_operations.i
.PHONY : MyWindow_operations.i

# target to generate assembly for a file
MyWindow_operations.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/MyWindow_operations.s
.PHONY : MyWindow_operations.s

# target to build an object file
base_tab.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/base_tab.o
.PHONY : base_tab.o

# target to preprocess a source file
base_tab.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/base_tab.i
.PHONY : base_tab.i

# target to generate assembly for a file
base_tab.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/base_tab.s
.PHONY : base_tab.s

# target to build an object file
demo_tab.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/demo_tab.o
.PHONY : demo_tab.o

# target to preprocess a source file
demo_tab.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/demo_tab.i
.PHONY : demo_tab.i

# target to generate assembly for a file
demo_tab.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/demo_tab.s
.PHONY : demo_tab.s

# target to build an object file
qt_layer.o:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/qt_layer.o
.PHONY : qt_layer.o

# target to preprocess a source file
qt_layer.i:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/qt_layer.i
.PHONY : qt_layer.i

# target to generate assembly for a file
qt_layer.s:
	$(MAKE) -f CMakeFiles/redblue.dir/build.make CMakeFiles/redblue.dir/qt_layer.s
.PHONY : qt_layer.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... redblue"
	@echo "... MyWindow.o"
	@echo "... MyWindow.i"
	@echo "... MyWindow.s"
	@echo "... MyWindow_files.o"
	@echo "... MyWindow_files.i"
	@echo "... MyWindow_files.s"
	@echo "... MyWindow_operations.o"
	@echo "... MyWindow_operations.i"
	@echo "... MyWindow_operations.s"
	@echo "... base_tab.o"
	@echo "... base_tab.i"
	@echo "... base_tab.s"
	@echo "... demo_tab.o"
	@echo "... demo_tab.i"
	@echo "... demo_tab.s"
	@echo "... qt_layer.o"
	@echo "... qt_layer.i"
	@echo "... qt_layer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

